language: node_js
node_js:
  - 8

before_install:
  npm install -g npm@latest

script:
  - npm run flow
  - npm test
  - npm run build:app
  - npm run pack
  - cd app/
  - npm install
  - npm test
  - npm run build

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $github_token
  local_dir: app/build
  on:
    branch: master
